/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id: "Wo5dMEP_Bb1",
    title: "Woman Deo Review : Secret v/s Spinz | Best Perfume For Women",
    videoLength:'11:28',
    views:'120k',
    thumbnail:"	https://i.ytimg.com/vi/1NNgGVdjZ4U/hqdefault.jpg?s…EIYAXABwAEG&rs=AOn4CLCSqqi78tIQRfouUCe40282r3WpNg",
    channelName: "Lax Styles",
    channelProfile:'https://yt3.ggpht.com/ytc/AKedOLToH0PxgQ7AJvcasJzavPLEzSEgnk3TnwEetpALsg=s48-c-k-c0x00ffffff-no-rj',
    description:"My first impressions on 4 new perfumes from the latest Intense series (2021) Body Perfumes by Wild Stone.",

  },
  {
    _id: "Wo5dMEP_Bb2",
    title:"Top 10 Best Deodorant For woman girls in 2021 in India",
    videoLength:'11:28',
    views:'234k',
    thumbnail:"https://i.ytimg.com/vi/i4W6OLDXefs/hqdefault.jpg?s…EIYAXABwAEG&rs=AOn4CLAf2l_Ko9EunOe0AMuJ8TCcXCABCA",
    channelName: "Beauty and Health Miracle",
    channelProfile:'https://yt3.ggpht.com/ytc/AKedOLQkVep1dxPNNfGlO5qWyr_ytLp5AlXXo6FrCdfB-g=s48-c-k-c0x00ffffff-no-rj',
    description:'My first impressions on 4 new perfumes from the latest Intense series (2021) Body Perfumes by Wild Stone.',

  },
  {
    _id: "Wo5dMEP_Bb3",
    title: "deodarant ₹ 199 | Ajmal wisal and Ajmal wisal daahab|",
    videoLength:'11:28',
    views:'24k',
    thumbnail:"	https://i.ytimg.com/vi/AZpWI-xmAXY/hqdefault.jpg?s…EIYAXABwAEG&rs=AOn4CLASHisbJLXqF-SUZUhsCf1axhCwlw",
    channelName: "Its1naved Khan",
    channelProfile:'https://yt3.ggpht.com/ytc/AKedOLRpOmfhk35EhPHA_i8YtE_wtcw-Z3DC_AulBs9P-g=s48-c-k-c0x00ffffff-no-rj',
    description:'My first impressions on 4 new perfumes from the latest Intense series (2021) Body Perfumes by Wild Stone.',
  },
  {
    _id: "Wo5dMEP_Bb4",
    title: "10 Best Perfume for Women | With Price | 2020 🔥🔥🔥",
    videoLength:'11:28',
    views:'45k',
    thumbnail:"https://i.ytimg.com/vi/XiTegknVFPk/hqdefault.jpg?s…EIYAXABwAEG&rs=AOn4CLDkHeCfkbUEvJgnO-P_zQDUn12Gfg",
    channelName: "ALL In One Idea Exchange",
    channelProfile:'https://yt3.ggpht.com/ytc/AKedOLSKFClBfALv5AnpFxsuS3eVwKWqrVndkbIcDyhRwQ=s48-c-k-c0x00ffffff-no-rj',
    description:'My first impressions on 4 new perfumes from the latest Intense series (2021) Body Perfumes by Wild Stone.',
  },
  {
    _id: "Wo5dMEP_Bb5",
    title: "Best Deodorant For Women|Nivea Deodorant For Women",
    videoLength:'11:28',
    views:'34k',
    thumbnail:"	https://i.ytimg.com/vi/FKfLZhUz4RY/hqdefault.jpg?s…EIYAXABwAEG&rs=AOn4CLDLj6k0r1UZ7-F9uq_52wkwwEEAAw",
    channelName: "Ddaily Review",
    channelProfile:'https://yt3.ggpht.com/ytc/AKedOLQhsRRYiClW49Bx6nRQA7rYXDTGuUwWjbMEeXIx=s48-c-k-c0x00ffffff-no-rj',
    description:'My first impressions on 4 new perfumes from the latest Intense series (2021) Body Perfumes by Wild Stone.',
  },
  {
    _id: "Wo5dMEP_Bb6",
    title: "Top 5 Deodorants Under 300 Rupees | Best Drugstore Deodorants",
    videoLength:'11:28',
    views:'345k',
    thumbnail:"https://i.ytimg.com/vi/Uy0VmizbobM/hqdefault.jpg?s…EIYAXABwAEG&rs=AOn4CLAKU_1AH8lGLTTeoyV-fz6w4MR8fA",
    channelName: "Foxy - Makeup Tips and Tutorials",
    channelProfile:'https://yt3.ggpht.com/ytc/AKedOLToH0PxgQ7AJvcasJzavPLEzSEgnk3TnwEetpALsg=s48-c-k-c0x00ffffff-no-rj',
    description:'My first impressions on 4 new perfumes from the latest Intense series (2021) Body Perfumes by Wild Stone.',
  },
  {
    _id: "Wo5dMEP_Bb7",
    title: "Amacon ka highest rated perfume *Blind Buy*",
    videoLength:'11:28',
    views:'89k',
    thumbnail:"	https://i.ytimg.com/vi/ceMCUIpq1gA/hqdefault.jpg?s…EIYAXABwAEG&rs=AOn4CLDhcQoJ5b5ECifyCLReIQ5p-xOm8Q",
    channelName: "Perfume Guru",
    channelProfile:'https://yt3.ggpht.com/ytc/AKedOLTj_VXB5WlnPKSPx0_M5e6rbeqbcMqHxZDovw6b=s48-c-k-c0x00ffffff-no-rj',
    description:'My first impressions on 4 new perfumes from the latest Intense series (2021) Body Perfumes by Wild Stone.',
  },
  {
    _id: "Wo5dMEP_Bb8",
    title: "Kashmir by M L Ramnarain Perfumers",
    videoLength:'11:28',
    views:'34k',
    thumbnail:"https://i.ytimg.com/vi/j7MdEMMlwxI/hqdefault.jpg?s…EIYAXABwAEG&rs=AOn4CLBrUPemg09serdZ-dX9O3IYa3NS5A",
    channelName: "Perfume Guru",
    channelProfile:'https://yt3.ggpht.com/ytc/AKedOLTj_VXB5WlnPKSPx0_M5e6rbeqbcMqHxZDovw6b=s48-c-k-c0x00ffffff-no-rj',
    description:'My first impressions on 4 new perfumes from the latest Intense series (2021) Body Perfumes by Wild Stone.',
  },
  {
    _id: "Wo5dMEP_Bb9",
    title: "Wild Stone Intense Body Perfumes (2021) Review | First Impressions",
    videoLength:'11:28',
    views:'234k',
    thumbnail:"https://i.ytimg.com/vi/5irXlitQ38M/hqdefault.jpg?s…EIYAXABwAEG&rs=AOn4CLBK_Oe1UMRTbEg4UCy8c2CQSpXMaA",
    channelName: "Perfume Guru",
    channelProfile:'https://yt3.ggpht.com/ytc/AKedOLTj_VXB5WlnPKSPx0_M5e6rbeqbcMqHxZDovw6b=s48-c-k-c0x00ffffff-no-rj',
    description:'My first impressions on 4 new perfumes from the latest Intense series (2021) Body Perfumes by Wild Stone.',
  },
  {
    _id: "Wo5dMEP_Bb10",
    title: "Titan Skinn Mediterranean Grove Review | Creed Aventus clone ?",
    videoLength:'11:28',
    views:'56k',
    thumbnail:"https://i.ytimg.com/vi/PtAOxmfd-m4/hqdefault.jpg?s…EIYAXABwAEG&rs=AOn4CLBtpe-466NuvqJinL_-bXx3iVGSow",
    channelName: "Perfume Guru",
    channelProfile:'https://yt3.ggpht.com/ytc/AKedOLTj_VXB5WlnPKSPx0_M5e6rbeqbcMqHxZDovw6b=s48-c-k-c0x00ffffff-no-rj',
    description:'My first impressions on 4 new perfumes from the latest Intense series (2021) Body Perfumes by Wild Stone.',
  },
  {
    _id: "Wo5dMEP_Bb11",
    title: "Wild Stone Forest Spice Review",
    videoLength:'11:28',
    views:'1M',
    thumbnail:"https://i.ytimg.com/vi/T-DbQv9-4_8/hqdefault.jpg?s…EIYAXABwAEG&rs=AOn4CLC1ZDBeJ7E50-ADaGC-tVUWb8_IPw",
    channelName: "Perfume Guru",
    channelProfile:'https://yt3.ggpht.com/ytc/AKedOLTj_VXB5WlnPKSPx0_M5e6rbeqbcMqHxZDovw6b=s48-c-k-c0x00ffffff-no-rj',
    description:'My first impressions on 4 new perfumes from the latest Intense series (2021) Body Perfumes by Wild Stone.',
  },
  {
    _id: "Wo5dMEP_Bb12",
    title: "Best Perfume For Men in India under 2000Rs| BEST PERFUME",
    videoLength:'11:28',
    views:'45k',
    thumbnail:"https://i.ytimg.com/vi/eRxeDykA8mU/hqdefault.jpg?s…EIYAXABwAEG&rs=AOn4CLBfsNe8nO0pVqLuf7zMvI9S0cSy7g",
    channelName: "What The Dude",
    channelProfile:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvR0dHWUvLG74m58jzWniwgBMSI3I1u4Y_6Q&usqp=CAU',
    description:'My first impressions on 4 new perfumes from the latest Intense series (2021) Body Perfumes by Wild Stone.',
  },
  {
    _id: "Wo5dMEP_Bb13",
    title: "Top 10 Summer Deodorants| Best summer Deo| best Budget",
    videoLength:'11:28',
    views:'2.3K',
    thumbnail:"https://i.ytimg.com/vi/cPOoQjANtMg/hqdefault.jpg?s…EIYAXABwAEG&rs=AOn4CLCpzAIeD56dKUSYX1lket-Lk-m3iw",
    channelName: "Dr Perfume",
    channelProfile:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvR0dHWUvLG74m58jzWniwgBMSI3I1u4Y_6Q&usqp=CAU',
    description:'My first impressions on 4 new perfumes from the latest Intense series (2021) Body Perfumes by Wild Stone.',
  },
  {
    _id: "Wo5dMEP_Bb14",
    title: "Top 5 Most Complimented Perfumes IN Budget for 2022",
    videoLength:'11:28',
    views:'1.5M',
    thumbnail:"https://i.ytimg.com/vi/4uJuWIBaka0/hqdefault.jpg?s…EIYAXABwAEG&rs=AOn4CLB4uQAbRJOtjJRgyE2R7InuNnGdGw",
    channelName: "Dr Perfume",
    channelProfile:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvR0dHWUvLG74m58jzWniwgBMSI3I1u4Y_6Q&usqp=CAU',
    description:'My first impressions on 4 new perfumes from the latest Intense series (2021) Body Perfumes by Wild Stone.',
  },
  {
    _id: "Wo5dMEP_Bb15",
    title: "The Man Company Blanc Body Perfume| Detailed Review",
    videoLength:'11:28',
    views:'123K',
    thumbnail:"https://i.ytimg.com/vi/GVfvMQUN8bw/hqdefault.jpg?s…EIYAXABwAEG&rs=AOn4CLC5XV-IbMHQh5LCJw67tyRo8AGdUQ",
    channelName: "Dr Perfume",
    channelProfile:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvR0dHWUvLG74m58jzWniwgBMSI3I1u4Y_6Q&usqp=CAU',
    description:'My first impressions on 4 new perfumes from the latest Intense series (2021) Body Perfumes by Wild Stone.',
  },
  // {
  //   _id: "Wo5dMEP_Bb16",
  //   title: "Hamidi Perfumes Alcohol Free | Budget Perfume in India 2022",
  //   videoLength:'11:28',
  //   views:'345K',
  //   thumbnail:"	https://i.ytimg.com/vi/6dgeZFjGJ9Q/hqdefault.jpg?s…EIYAXABwAEG&rs=AOn4CLDHXrt4WnXUSRU7HvWO0g5b2aj4zg",
  //   channelName: "Frags Talk",
  //   channelProfile:'	https://yt3.ggpht.com/qFAYgNE4-xZ5IYDV50BqbmnRRXC0…YxOlis1w7RWJ7l4NEVLlpm-=s48-c-k-c0x00ffffff-no-rj',
  //   description:'My first impressions on 4 new perfumes from the latest Intense series (2021) Body Perfumes by Wild Stone.',
  // }
  
];
